package moe.atalanta.accounts.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import moe.atalanta.accounts.entity.Accounts;
import moe.atalanta.accounts.entity.Users;

import moe.atalanta.accounts.entity.AccountsDao;
import moe.atalanta.accounts.entity.UsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountsDaoConfig;
    private final DaoConfig usersDaoConfig;

    private final AccountsDao accountsDao;
    private final UsersDao usersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountsDaoConfig = daoConfigMap.get(AccountsDao.class).clone();
        accountsDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        accountsDao = new AccountsDao(accountsDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);

        registerDao(Accounts.class, accountsDao);
        registerDao(Users.class, usersDao);
    }
    
    public void clear() {
        accountsDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
    }

    public AccountsDao getAccountsDao() {
        return accountsDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

}
